"""
Final novel assembly — takes the winning StoryState, assembles chapters into
a complete novel (Markdown), and generates eval_log.json.
"""

import json
import os
from datetime import datetime

from .models import StoryConfig, StoryState, PreActorResult
from .utils import logger, safe_filename
from .naming import generate_chapter_title as naming_chapter_title
from .prompts import FRONT_MATTER_PROMPT

FRONT_MATTER_LABELS = {
    "toc": "目录",
    "epigraph": "引言 / 引子",
    "prologue": "楔子",
    "characters": "人物表",
}


async def generate_front_matter(
    config: StoryConfig, story_name: str, novel_text: str,
    npx_engine=None, llm_client=None,
) -> str:
    """
    Generate front matter based on user-selected options. Returns Markdown text.
    - TOC: auto-generated from chapter headings
    - Characters: extracted from story (rule-based)
    - Epigraph/Prologue: LLM-generated
    """
    selected = config.front_matter
    if not selected:
        return ""

    parts = []

    # 1. Epigraph (引言)
    if "epigraph" in selected:
        tags = " · ".join([story_name, config.protagonist_name])
        parts.append(
            f"> *\"{story_name}\"*\n>\n"
            f"> *千墨选一，落纸成书*\n>\n"
            f"> — {tags}\n"
        )

    # 2. TOC (目录) — auto-generated
    if "toc" in selected:
        toc = ["# 目录\n"]
        for line in novel_text.split("\n"):
            if line.startswith("## "):
                title = line[3:].strip()
                toc.append(f"- {title}")
        parts.append("\n".join(toc))

    # 3. Prologue (楔子) — LLM
    if "prologue" in selected and llm_client:
        try:
            prompt = (
                f"请为此小说写一段 200-400 字的楔子（Prologue），"
                f"以神秘、吸引人的笔调暗示故事的核心冲突，但不透露结局。\n"
                f"主角: {config.protagonist_name}\n"
                f"世界: {config.world_setting[:200]}\n"
                f"摘要: {novel_text[:600]}"
            )
            text, _ = await llm_client.call(
                prompt, "请写一段楔子。", temperature=0.8, max_tokens=800,
            )
            parts.append(f"# 楔子\n\n{text.strip()}")
        except Exception as e:
            logger.warning(f"楔子生成失败: {e}")

    # 4. Characters (人物表) — extracted from story
    if "characters" in selected and npx_engine:
        try:
            from .naming import extract_keywords
            kw = extract_keywords(config, novel_text)
            char_lines = ["# 人物表\n", f"| 角色 | 描述 |", "|------|------|"]
            # Protagonist always first
            char_lines.append(
                f"| {config.protagonist_name} | "
                f"{config.protagonist_traits[:60]}... |"
            )
            # Others from keywords
            for loc in kw.locations[:3]:
                char_lines.append(f"| {loc}的居民 | 来自{loc} |")
            parts.append("\n".join(char_lines))
        except Exception as e:
            logger.warning(f"人物表生成失败: {e}")

    if not parts:
        return ""

    return "\n\n---\n\n".join(parts) + "\n\n---\n\n"


def generate_novel(result: PreActorResult) -> str:
    """
    Generate the final novel as Markdown text from the winning version.

    Returns the novel text as a string.
    """
    winning_version = _get_winning_version(result)
    if winning_version is None:
        return "# 错误：没有可用的版本\n\n预演未能生成有效故事。请检查配置并重试。"

    config = result.config
    lines = []

    # Title page
    lines.append(f"# {config.protagonist_name}的传奇")
    lines.append("")
    lines.append(f"> 由 选墨集（Sifted-Ink）自动生成")
    lines.append(f"> 生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"> 模型: {config.model}")
    lines.append(f"> 总章节: {winning_version.chapter_count}")
    lines.append(f"> 总字数: 约{winning_version.total_words}字")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Assemble chapters
    naming_style = result.config.naming_style
    protagonist = result.config.protagonist_name
    for ch in winning_version.chapters:
        title = naming_chapter_title(
            ch.director_notes or ch.content[:200], ch.number,
            naming_style, protagonist,
        )
        lines.append(f"## {title}")
        lines.append("")
        lines.append(ch.content.strip())
        lines.append("")

    # Epilogue / ending note
    if winning_version.reached_ending:
        lines.append("---")
        lines.append("")
        lines.append("*（全书完）*")
        lines.append("")
        lines.append("<sub>Generated by 选墨集 / Sifted-Ink</sub>")
        lines.append("")

    return "\n".join(lines)


def generate_novel_for_version(result: PreActorResult, version: StoryState) -> str:
    """Generate novel text for a specific version (not necessarily the winner)."""
    config = result.config
    lines = []
    lines.append(f"# {config.protagonist_name}的传奇")
    lines.append("")
    lines.append(f"> 由 选墨集（Sifted-Ink）自动生成")
    lines.append(f"> 版本: #{version.version_id}")
    lines.append(f"> 生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"> 模型: {config.model}")
    lines.append(f"> 总章节: {version.chapter_count}")
    lines.append(f"> 总字数: 约{version.total_words}字")
    lines.append("")
    lines.append("---")
    lines.append("")

    naming_style = result.config.naming_style
    protagonist = result.config.protagonist_name
    for ch in version.chapters:
        title = naming_chapter_title(
            ch.director_notes or ch.content[:200], ch.number,
            naming_style, protagonist,
        )
        lines.append(f"## {title}")
        lines.append("")
        lines.append(ch.content.strip())
        lines.append("")

    if version.reached_ending:
        lines.append("---")
        lines.append("")
        lines.append("*（全书完）*")
        lines.append("")
        lines.append("<sub>Generated by 选墨集 / Sifted-Ink</sub>")
        lines.append("")

    return "\n".join(lines)


def save_novel(result: PreActorResult, output_dir: str = ".",
               story_name: str = "") -> str:
    """
    Save the generated novel to a markdown file.
    Returns the file path.
    """
    novel_text = generate_novel(result)
    filename = _make_filename(result, story_name)
    filepath = os.path.join(output_dir, f"{filename}.md")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(novel_text)

    logger.info(f"📖 小说已保存至: {filepath}")
    return filepath


def _make_filename(result: PreActorResult, story_name: str = "") -> str:
    """Generate a filename: {story_name}_{timestamp}_v{version} or fallback."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    vtag = f"v{result.winning_version_id}"
    if story_name:
        name = safe_filename(story_name, max_len=30)
    else:
        name = safe_filename(f"{result.config.protagonist_name}_传奇", max_len=30)
    return f"{name}_{timestamp}_{vtag}"


def generate_eval_log(result: PreActorResult, story_meta: dict | None = None) -> dict:
    """
    Generate the evaluation log as a structured dictionary.
    Optionally includes story naming metadata.
    """
    log = {
        "generated_at": datetime.now().isoformat(),
        "story_meta": story_meta or {},
        "config": {
            "protagonist_name": result.config.protagonist_name,
            "protagonist_traits": result.config.protagonist_traits,
            "world_setting": result.config.world_setting,
            "story_start": result.config.story_start,
            "story_end": result.config.story_end,
            "target_word_count": result.config.target_word_count,
            "model": result.config.model,
            "num_versions": result.config.num_versions,
            "max_npcs": result.config.max_npcs,
            "max_chapters": result.config.max_chapters,
            "total_token_budget": result.config.total_token_budget,
        },
        "summary": {
            "total_tokens_used": result.total_tokens_used,
            "time_elapsed_seconds": result.time_elapsed_seconds,
            "winning_version_id": result.winning_version_id,
            "user_selected": result.user_selected,
            "total_versions": len(result.versions),
            "completed_versions": sum(1 for v in result.versions if v.reached_ending),
        },
        "versions": [],
    }

    for v in result.versions:
        eval_data = next(
            (e for e in result.evaluations if e.version_id == v.version_id), None
        )

        version_log = {
            "version_id": v.version_id,
            "completed": v.reached_ending,
            "terminated_early": v.terminated_early,
            "termination_reason": v.termination_reason,
            "chapter_count": v.chapter_count,
            "total_words": v.total_words,
            "tokens_used": v.total_tokens_used,
            "npc_log": {
                "total_npcs_created": len(v.active_npcs) + len(v.npc_graveyard),
                "active_at_end": len([n for n in v.active_npcs if n.alive]),
                "npcs": [],
                "graveyard": [],
            },
            "chapters": [],
        }

        # NPC details
        for npc in v.active_npcs:
            version_log["npc_log"]["npcs"].append({
                "id": npc.id,
                "name": npc.name,
                "role": npc.role,
                "intro_chapter": npc.intro_chapter,
                "exit_chapter": npc.exit_chapter,
            })
        for npc in v.npc_graveyard:
            version_log["npc_log"]["graveyard"].append({
                "id": npc.id,
                "name": npc.name,
                "role": npc.role,
                "intro_chapter": npc.intro_chapter,
                "exit_chapter": npc.exit_chapter,
            })

        # Chapter summaries
        for ch in v.chapters:
            version_log["chapters"].append({
                "number": ch.number,
                "word_count": len(ch.content),
                "token_cost": ch.token_cost,
                "director_notes": ch.director_notes[:200],
                "protagonist_action": {
                    "action": ch.protagonist_action.action if ch.protagonist_action else "none",
                    "emotion": ch.protagonist_action.emotion if ch.protagonist_action else "none",
                },
                "npc_actions_count": len(ch.npc_actions),
                "npcs_introduced": [n.name for n in ch.npcs_introduced],
                "npcs_exited": ch.npcs_exited,
            })

        # Evaluation
        if eval_data:
            version_log["evaluation"] = {
                "dramatic_tension": eval_data.dramatic_tension,
                "character_growth": eval_data.character_growth,
                "logic_consistency": eval_data.logic_consistency,
                "ending_alignment": eval_data.ending_alignment,
                "total_score": eval_data.total_score,
                "notes": eval_data.evaluator_notes,
            }

        log["versions"].append(version_log)

    return log


def save_eval_log(result: PreActorResult, output_dir: str = ".",
                  story_name: str = "", story_meta: dict | None = None) -> str:
    """
    Save the evaluation log to a JSON file.
    Returns the file path.
    """
    log = generate_eval_log(result, story_meta)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    vtag = f"v{result.winning_version_id}"
    name_part = safe_filename(story_name, max_len=30) if story_name else "eval"
    filepath = os.path.join(output_dir, f"eval_{name_part}_{timestamp}_{vtag}.json")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)

    logger.info(f"📊 评估日志已保存至: {filepath}")
    return filepath


def _get_winning_version(result: PreActorResult) -> StoryState | None:
    """Get the winning version from a PreActorResult."""
    for v in result.versions:
        if v.version_id == result.winning_version_id:
            return v
    return None


def _generate_chapter_title(ch) -> str:
    """Generate a chapter title from director notes or chapter content."""
    notes = ch.director_notes
    if notes:
        # Try to extract a title-like phrase
        # Just use the first sentence or first 30 chars
        first_part = notes.split("。")[0].split("；")[0].strip()
        if len(first_part) > 3:
            return f"第{ch.number}章 {first_part}"

    return f"第{ch.number}章"
